
-- COPY AND RUN THIS IN SUPABASE SQL EDITOR

-- 1. Enable RLS (Row Level Security) on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE books ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE inquiries ENABLE ROW LEVEL SECURITY;

-- 2. POLICIES FOR 'profiles'
CREATE POLICY "Public profiles are viewable by everyone" ON profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

-- 3. POLICIES FOR 'books'
CREATE POLICY "Books are viewable by everyone" ON books FOR SELECT USING (true);
CREATE POLICY "Authenticated users can insert books" ON books FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Users can update own books" ON books FOR UPDATE USING (auth.uid() = owner_id);

-- 4. POLICIES FOR 'orders'
CREATE POLICY "Users can create orders" ON orders FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can view own orders" ON orders FOR SELECT USING (auth.uid() = user_id);

-- 5. POLICIES FOR 'cart_items'
CREATE POLICY "Users can manage their own cart" ON cart_items FOR ALL USING (auth.uid() = user_id);

-- 6. POLICIES FOR 'forum_posts'
CREATE POLICY "Forum posts are viewable by everyone" ON forum_posts FOR SELECT USING (true);
CREATE POLICY "Authenticated users can create posts" ON forum_posts FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update posts" ON forum_posts FOR UPDATE USING (auth.role() = 'authenticated');

-- 7. POLICIES FOR 'forum_replies'
CREATE POLICY "Replies are viewable by everyone" ON forum_replies FOR SELECT USING (true);
CREATE POLICY "Authenticated users can reply" ON forum_replies FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Authenticated users can update replies" ON forum_replies FOR UPDATE USING (auth.role() = 'authenticated');

-- 8. POLICIES FOR 'inquiries'
CREATE POLICY "Anyone can insert inquiries" ON inquiries FOR INSERT WITH CHECK (true);

-- 9. ADD MISSING COLUMNS (Run this to fix "column not found" errors)
ALTER TABLE books ADD COLUMN IF NOT EXISTS security_deposit NUMERIC DEFAULT 0;
ALTER TABLE books ADD COLUMN IF NOT EXISTS average_rating NUMERIC DEFAULT 0;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS security_deposit NUMERIC DEFAULT 0;
ALTER TABLE cart_items ADD COLUMN IF NOT EXISTS rent_months INTEGER DEFAULT 1;

-- 10. FIX ID COLUMN AUTO-INCREMENT (Run this if you get "null value in column id" error)
-- This makes the ID column auto-generate values if none is provided.
ALTER TABLE books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
